# Generated by Django 2.2.16 on 2020-11-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverviewExtendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_outside', models.BooleanField(default=False)),
                ('course_link', models.TextField(blank=True, max_length=1024, null=True)),
                ('course_overview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_ext_info', to='course_overviews.CourseOverview')),
            ],
        ),
    ]
