# Generated by Django 2.2.16 on 2020-12-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0023_courseoverviewextendinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewextendinfo',
            name='course_grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseoverviewextendinfo',
            name='course_highlight',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseoverviewextendinfo',
            name='course_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoverviewextendinfo',
            name='course_recommend_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverviewextendinfo',
            name='course_link',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverviewextendinfo',
            name='course_overview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview'),
        ),
    ]
