# Generated by Django 2.2.16 on 2020-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_auto_20201223_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverviewextendinfo',
            name='course_recommend_level',
            field=models.SmallIntegerField(default=5),
        ),
    ]
