# Generated by Django 2.2.16 on 2020-12-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0005_mapprofileextresults_mapstudentprofile_maptestcheckitem'),
        ('course_overviews', '0025_auto_20201223_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewextendinfo',
            name='course_ccss_items',
            field=models.ManyToManyField(to='pdfexam.MapTestCheckItem'),
        ),
    ]
