# Generated by Django 2.2.16 on 2020-12-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_courseoverviewextendinfo_course_ccss_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverviewextendinfo',
            name='course_overview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_ext_info', to='course_overviews.CourseOverview'),
        ),
    ]
