# Generated by Django 2.2.16 on 2020-12-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_auto_20201224_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverviewextendinfo',
            name='course_price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseoverviewextendinfo',
            name='course_recommend_level',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
