# Generated by Django 2.2.16 on 2020-11-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20201115_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollmentinfo',
            name='course_enrolled',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_detail', to='student.CourseEnrollment'),
        ),
    ]
