# Generated by Django 2.2.16 on 2020-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20201117_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollmentinfo',
            name='course_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
