# Generated by Django 2.2.16 on 2020-12-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0003_auto_20201204_0751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earlyliteracyskillsetscores',
            unique_together={('phone_number', 'TestDate')},
        ),
    ]
