# Generated by Django 2.2.16 on 2020-12-23 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0004_auto_20201217_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapStudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers.', regex='^\\+?1?\\d*$')])),
                ('ExportDate', models.DateField()),
                ('ExportStaff', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=20)),
                ('FamilyName', models.CharField(max_length=20)),
                ('Grade', models.CharField(max_length=10)),
                ('TestCategory', models.CharField(max_length=20)),
                ('Standard_Error', models.CharField(max_length=16)),
                ('Possible_range', models.CharField(max_length=16)),
                ('TestDate', models.DateField()),
                ('TestDuration', models.CharField(max_length=10)),
                ('Rapid_Guessing_Percent', models.CharField(max_length=10)),
                ('Est_Impact_of_Rapid_Guessing_Percent_on_RIT', models.CharField(max_length=10)),
                ('Growth', models.CharField(max_length=50)),
                ('Semester', models.CharField(max_length=30)),
                ('Score', models.CharField(max_length=10)),
                ('HIGHLIGHTS', models.CharField(max_length=2000)),
                ('Group_by', models.CharField(max_length=50)),
                ('Grades', models.CharField(max_length=50)),
                ('Concepts_to', models.CharField(max_length=50)),
                ('Informational_Text_Key_Ideas_and_Details_SCORE', models.CharField(max_length=10)),
                ('Informational_Text_Key_Ideas_and_Details_STANDARD_ERROR', models.CharField(max_length=16)),
                ('Vocabulary_Acquisition_and_Use_SCORE', models.CharField(max_length=10)),
                ('Vocabulary_Acquisition_and_Use_STANDARD_ERROR', models.CharField(max_length=16)),
                ('Informational_Text_Language_Craft_and_Structure_SCORE', models.CharField(max_length=10)),
                ('Informational_Text_Language_Craft_and_Structure_STANDARD_ERROR', models.CharField(max_length=16)),
                ('Literary_Text_Language_Craft_and_Structure_SCORE', models.CharField(max_length=10)),
                ('Literary_Text_Language_Craft_and_Structure_STANDARD_ERROR', models.CharField(max_length=16)),
                ('Literary_Text_Key_Ideas_and_Details_SCORE', models.CharField(max_length=10)),
                ('Literary_Text_Key_Ideas_and_Details_STANDARD_ERROR', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MapTestCheckItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_domain', models.CharField(max_length=64)),
                ('l2_sub_domain', models.CharField(max_length=64)),
                ('l3_grade', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=10, unique=True)),
                ('item_desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MapProfileExtResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_level', models.CharField(max_length=50)),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_items', to='pdfexam.MapTestCheckItem')),
                ('recommend_description', models.TextField(null=True)),
                ('map_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_ext_results', to='pdfexam.MapStudentProfile')),
            ],
        ),
    ]
