# Generated by Django 2.2.16 on 2020-12-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0006_auto_20201226_0742'),
    ]

    operations = [

    ]
