# Generated by Django 2.2.16 on 2020-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0007_auto_20201227_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstudentprofile',
            name='map_pdf_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mapstudentprofile',
            unique_together={('phone_number', 'TestDate')},
        ),
    ]
