# Generated by Django 2.2.16 on 2020-12-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0008_auto_20201230_0855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapprofileextresults',
            unique_together={('map_student_profile', 'check_item')},
        ),
    ]
