# Generated by Django 2.2.16 on 2021-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0009_auto_20201230_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstudentprofile',
            name='foundational_skills',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='language_and_writing',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='language_understarnd_edit_for_grammar_usage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='language_understarnd_edit_for_mechanics',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='literature_and_informational_text',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='vocabulary_use_and_function',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='writing_write_revise_texts_for_purpose_and_audience',
            field=models.CharField(default='', max_length=10),
        ),
    ]
