# Generated by Django 2.2.16 on 2021-01-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0010_auto_20210116_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstudentprofile',
            name='map_pdf_url_all_items',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapstudentprofile',
            name='map_pdf_url_all_items_no_txt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
