# Generated by Django 2.2.16 on 2021-02-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0011_auto_20210121_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapstudentprofile',
            old_name='language_understarnd_edit_for_grammar_usage',
            new_name='language_understand_edit_for_grammar_usage',
        ),
        migrations.RenameField(
            model_name='mapstudentprofile',
            old_name='language_understarnd_edit_for_mechanics',
            new_name='language_understand_edit_for_mechanics',
        ),
        migrations.AlterField(
            model_name='maptestcheckitem',
            name='item_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='maptestcheckitem',
            name='l3_grade',
            field=models.CharField(max_length=20),
        ),
    ]
