# Generated by Django 2.2.16 on 2021-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0013_auto_20210207_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstudentprofile',
            name='map_pdf_url_instructional_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mapstudentprofile',
            unique_together={('phone_number', 'TestDate', 'Growth')},
        ),
    ]
