# Generated by Django 2.2.16 on 2021-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0014_auto_20210223_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstudentprofile',
            name='map_growth_pic_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
