# Generated by Django 2.2.16 on 2021-03-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0015_mapstudentprofile_map_growth_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarReadingTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('stu_name', models.CharField(default='', max_length=50)),
                ('date_range', models.CharField(default='', max_length=40)),
                ('benchmark_type', models.CharField(default='', max_length=40)),
                ('stu_id', models.CharField(default='', max_length=60)),
                ('grade', models.CharField(default='', max_length=10)),
                ('school', models.CharField(default='', max_length=40)),
                ('test_date', models.DateField()),
                ('teacher', models.CharField(default='', max_length=40)),
                ('class_group', models.CharField(default='', max_length=40)),
                ('scaled_score', models.IntegerField(blank=True, default=0, null=True)),
                ('percentile_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('grade_equivalent', models.FloatField(blank=True, default=0.0, null=True)),
                ('instructional_reading_level', models.FloatField(blank=True, default=0.0, null=True)),
                ('estimated_oral_fluency', models.IntegerField(blank=True, default=0, null=True)),
                ('literature_key_ideas_and_details', models.IntegerField(blank=True, default=0, null=True)),
                ('literature_craft_and_structure', models.IntegerField(blank=True, default=0, null=True)),
                ('literature_range_of_reading_and_text_complexity', models.IntegerField(blank=True, default=0, null=True)),
                ('information_text_key_ideas_and_details', models.IntegerField(blank=True, default=0, null=True)),
                ('information_text_craft_and_structure', models.IntegerField(blank=True, default=0, null=True)),
                ('information_text_integration_of_knowledge_and_ideas', models.IntegerField(blank=True, default=0, null=True)),
                ('information_text_range_of_reading_and_text_complexity', models.IntegerField(blank=True, default=0, null=True)),
                ('language_vocabulary_acquisition_and_use', models.IntegerField(blank=True, default=0, null=True)),
                ('lexile_range', models.CharField(default='', max_length=20)),
                ('test_duration', models.CharField(default='', max_length=40)),
                ('demographics', models.CharField(default='', max_length=20)),
                ('scale_type', models.CharField(default='', max_length=20)),
            ],
            options={
                'unique_together': {('phone_number', 'test_date')},
            },
        ),
        migrations.CreateModel(
            name='StarReadingTestInfoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_score', models.IntegerField(blank=True, default=0, null=True)),
                ('item_desc', models.CharField(default='', max_length=256)),
                ('domain_name', models.CharField(default='', max_length=100)),
                ('ccss_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccss_items', to='pdfexam.MapTestCheckItem')),
                ('star_reading_test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_reading_report', to='pdfexam.StarReadingTestInfo')),
            ],
            options={
                'unique_together': {('star_reading_test_info', 'ccss_item')},
            },
        ),
    ]
