# Generated by Django 2.2.16 on 2021-03-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0017_auto_20210305_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='starreadingtestinfo',
            name='main_pdf_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='starreadingtestinfo',
            name='simple_pdf_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
