# Generated by Django 2.2.16 on 2021-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0018_auto_20210310_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarReadingBenchmarkColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, unique=True)),
                ('red', models.FloatField(default=0.2)),
                ('yellow', models.FloatField(default=0.1)),
                ('blue', models.FloatField(default=0.1)),
                ('green', models.FloatField(default=0.6)),
            ],
        ),
    ]
