# Generated by Django 2.2.16 on 2021-03-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexam', '0019_starreadingbenchmarkcolors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapprofileextresults',
            name='recommend_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mapstudentprofile',
            name='map_pdf_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='starreadingtestinforeport',
            name='item_desc',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
